#!/bin/bash

export REALHOME=`greadlink -f $HOME`

export PROMPT_COMMAND="_prompt_cmd"

_prompt_cmd() {
	_set_color $?
	_set_title
}

_save_history() {
	# Append new history lines to the history file instead of waiting for the
	# end of session.
	history -a
	# Note I don't care to actually reload any other history that's been added
	# by other sessions. If I want *everything* I can open a new bash session.
	# Or load it manually with `history -n`.
}

_set_title() {
	local DIR
	local short_dir
	DIR=$(pwd|sed -e "s!$REALHOME!~!"|sed -e "s!$HOME!~!");
	if (( ${#DIR} > 30 )); then
		short_dir=${DIR:0:12}...${DIR:${#DIR}-15}
	else
		short_dir=$DIR
	fi
	if [[ ( ${TERM:0:5} == "xterm" ) || ( ${TERM:0:5} == "gnome" ) ]]; then
		echo -e -n "\033]0;${short_dir}\a"
	fi
}

_set_color() {
	local last_status=$1
	local color
	if (( $last_status )); then
		color="\[\033[0;31m\]"
	else
		color="\[\033[0;36m\]"
	fi
	export PS1="$color[\W]\\$ \[\033[0m\]"
}
