#!/bin/bash

export REALHOME=`readlink -f $HOME`

if [[ ${TERM:0:5} == "xterm" ]]; then
	SET_TITLE='; echo -e -n "\e]0;$CurDir\a"'
else
	SET_TITLE=''
fi

export PROMPT_COMMAND='DIR=`pwd|sed -e "s!$REALHOME!~!"|sed -e "s!$HOME!~!"`; if [ ${#DIR} -gt 30 ]; then CurDir=${DIR:0:12}...${DIR:${#DIR}-15}; else CurDir=$DIR; fi'"$SET_TITLE"
export SETCOLOR_CMD='if [ $(whoami) == root ]; then PROMPT_COLOR="\[\e[0;31m\]"; else PROMPT_COLOR="\[\e[0;36m\]"; fi; export PS1="$PROMPT_COLOR[\h|\W]\\$ \[\e[0m\]"'
export PROMPT_COMMAND="$PROMPT_COMMAND; $SETCOLOR_CMD"

export PS1="\[\e[0;36m\][\h|\W]$PROMPT_COLOR\\$ \[\e[0m\]"
