#!/bin/bash

export REALHOME=`greadlink -f $HOME`

if [[ ( ${TERM:0:5} == "xterm" ) || ( ${TERM:0:5} == "gnome" ) ]]; then
	SET_TITLE='; echo -e -n "\033]0;$CurDir\a"'
else
	SET_TITLE=''
fi

export PROMPT_COMMAND='DIR=`pwd|sed -e "s!$REALHOME!~!"|sed -e "s!$HOME!~!"`; if [ ${#DIR} -gt 30 ]; then CurDir=${DIR:0:12}...${DIR:${#DIR}-15}; else CurDir=$DIR; fi'"$SET_TITLE"
export SETCOLOR_CMD='if [ $(whoami) == root ]; then PROMPT_COLOR="\[\033[0;31m\]"; else PROMPT_COLOR="\[\033[0;36m\]"; fi; export PS1="$PROMPT_COLOR[\h|\W]\\$ \[\033[0m\]"'
export PROMPT_COMMAND="$PROMPT_COMMAND; $SETCOLOR_CMD"

export PS1="\[\033[0;36m\][\h|\W]$PROMPT_COLOR\\$ \[\033[0m\]"
